### ISSUE TITLE
Course still shows in Progress

### ISSUE THREAD

**Issue by ahmedmq** [ModernAppsNinja/CourseFeedback#27]
After completing all sections, course still shows in progress

**Comment by afewellvmware** [comment]
Hi @ahmedmq I see that you completed all requirements, when you log into the course and go to the progress tab, you should see an option to "Request Certificate", and once you click that you should be able to see your course certificate. You may still see the course in your dashboard, because the course itself runs perpetually and does not have a specific end date. But once you get your certificate you can consider the course done and completed. 

Please let me know if you cannot see the "Request Certificate" link on the progress tab. 

Thanks so much!

**Comment by ahmedmq** [comment]
I can see the request certificate
