### ISSUE TITLE
Course Feedback

### ISSUE THREAD

**Issue by pivotal-gordon-krull** [ModernAppsNinja/CourseFeedback#55]
The course provided a good high level introduction to the portfolio, however I wish it was a little more engaging than just watching a video.

**Comment by afewellvmware** [comment]
Thanks so much for the feedback @pivotal-gordon-krull I do plan to add some to this, but also part of the reason there are not many additional exercises in this course is to have more smaller course modules rather than fewer larger modules, so there are several courses that would have had more exercises, but were instead divided into separate modules. For example, TMC 101/201 was originally meant to be one course, but we broke it into 2 and put all lab exercises in 201. We intend to be very lab centric at all levels other than 100 level, partially because we have had requests for intro level materials to be able to provide some technical foundations for managerial roles that may not desire as much hands on. Another consideration is that many users may be interested in a TMC or a TKG specific training and find they need to take the Tanzu Portfolio Overview as a pre-requisite for most other courses, so especially for this course a strong focus on brevity is important, not at the expense of being thorough, but we do intend that the overview will be mostly used by people who would take additional follow on modules to learn more details about the portfolio or a specific product. One other thing we plan to introduce soon are learning paths where someone could get a credential for some sequence of courses. This is still being planned but for example something like a platform operations learning path that would include intro to tanzu, tmc 101/201, tkg 101/201, TO 101/201 and TSM 101/201 courses, and then some completion certificate or credential recognizing the students completion of the learning path. This would help ensure that people who start off on a small module are encouraged to continue with materials and clear to student exactly what sequence of courses make sense for a role or learning objective. 

Thank you!
