### ISSUE TITLE
Good content

### ISSUE THREAD

**Issue by kevinvmware** [ModernAppsNinja/CourseFeedback#60]
The only suggestion I would make is to turn on annotations during the presentation so that mouse movements and/or annotations can draw the viewer's eye to the appropriate section on the slide.

The white mouse pointer on a mostly white slide isn't easily seen and viewers can lose focus because they will typically try to read everything on the slide first.

**Comment by afewellvmware** [comment]
Thanks so much Kevin! I do hope to get annotations at some point, I am a little scared of using these right now because we only have the autogenerated youtube transcripts which are pretty bad and can sometimes make very unprofessional incorrect guesses about the captioning. I dont foresee any time in the near future where we would have ability to hire people to transcribe, but I know machine learning algorithms are improving a lot in this area so perhaps its feasible to find a solution that can do a decent job automating the transcription ... I will keep an eye out. 

And great point about the mouse pointer I assume there may be some setting in my screen capture tool to better highlight the mouse or I know solutions for this exist so I will try to make that change immediately. 

Thanks again !
